# Generated by Django 6.1.1 on 2026-10-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trip_total_distance_miles_trip_total_driving_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='total_distance_miles',
            new_name='distance_miles',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='total_driving_hours',
            new_name='duration_hours',
        ),
        migrations.AddField(
            model_name='trip',
            name='plan',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.JSONField(default=dict),
        ),
    ]
